name: CI/CD Pipeline - Zesty Bite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: mydockerhubuser/zestybite-app

jobs:
  build-and-push:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest

  test:
    name: Pull image & run tests
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull image and run tests (container)
        run: |
          docker pull ${{ env.IMAGE_NAME }}:${{ github.sha }}
          # example test run; change to your app's test command
          docker run --rm ${{ env.IMAGE_NAME }}:${{ github.sha }} npm test

  deploy-ec2:
    name: Deploy to EC2 via SSH
    needs: [ build-and-push, test ]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 (SSH)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # on remote EC2: login to Docker Hub, pull latest image, restart container
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker pull ${{ env.IMAGE_NAME }}:latest
            docker stop zesty_app || true
            docker rm zesty_app || true
            docker run -d --name zesty_app -p 80:80 --restart unless-stopped ${{ env.IMAGE_NAME }}:latest
