name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # or master (change if needed)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push the image to your Docker Hub repo
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: maryamsohail123/zesty-bite:latest

      # Step 5: Confirmation message
      - name: Image digest
        run: echo "✅ Image pushed successfully: maryamsohail123/zesty-bite:latest"
