name: CI/CD Pipeline - Zesty Bite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_push_deploy:
    name:  Build, Push & Deploy to AWS EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t maryamsohail123/zesty-bite:latest -f zestybites/Dockerfile zestybites
          docker push maryamsohail123/zesty-bite:latest

      
